runtime: python39
entrypoint: gunicorn -b :$PORT app:app

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  max_concurrent_requests: 40

env_variables:
  MAX_CONCURRENT_CALLS: "40"
#These keys should only be defined in the production environment
  # PROJECT_ID: "project-id"
  # REGION: "region"
  # MODEL_NAME: "model-name"

handlers:
  - url: /health
    script: auto
    secure: always

  - url: /.*
    script: auto
    secure: always