name: Debug Authentication

on:
  workflow_dispatch:

jobs:
  debug-auth:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Debug Service Account Key
      run: |
        cd cloud-server
        echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' > credentials.json
        
        echo "=== Checking file size ==="
        ls -la credentials.json
        
        echo "=== Checking first and last lines ==="
        head -n 2 credentials.json
        echo "..."
        tail -n 2 credentials.json
        
        echo "=== Validating JSON ==="
        if python3 -c "import json; json.load(open('credentials.json'))"; then
          echo "✅ JSON is valid"
        else
          echo "❌ JSON is invalid!"
          exit 1
        fi
        
        echo "=== Checking required fields ==="
        python3 -c "
        import json
        data = json.load(open('credentials.json'))
        required = ['type', 'project_id', 'private_key_id', 'private_key', 'client_email']
        for field in required:
            if field in data:
                print(f'✅ {field}: present')
            else:
                print(f'❌ {field}: missing')
                exit(1)
        print(f'Project ID in JSON: {data.get(\"project_id\", \"NOT_FOUND\")}')
        "

    - name: Test Authentication Method 1
      run: |
        cd cloud-server
        echo "=== Testing direct activation ==="
        gcloud auth activate-service-account --key-file=credentials.json
        gcloud config set project ${{ secrets.PROJECT_ID }}
        gcloud auth list
        echo "=== Testing project access ==="
        gcloud projects describe ${{ secrets.PROJECT_ID }}

    - name: Test Authentication Method 2
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        project_id: ${{ secrets.PROJECT_ID }}
        export_default_credentials: true

    - name: Test after setup-gcloud action
      run: |
        echo "=== After setup-gcloud action ==="
        gcloud auth list
        gcloud config list project
        gcloud projects describe ${{ secrets.PROJECT_ID }}