name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      confirm_production:
        description: 'Type "DEPLOY" to confirm'
        required: true
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Validate
      run: |
        if [ "${{ github.event.inputs.confirm_production }}" != "DEPLOY" ]; then
          echo "Error:  Must type 'DEPLOY'"
          exit 1
        fi
    
    - name: Setup
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        project_id: ${{ secrets.PROJECT_ID }}
        export_default_credentials: true
    
    - name: Test auth
      run: |
        gcloud auth list
        echo "Success:  Authentication successful"
    
    - name: Deploy
      run: |
        cd cloud-server
        NEW_VERSION="v$(date +%Y%m%d-%H%M)"
        echo "🚀 Deploying ${NEW_VERSION}..."
        gcloud app deploy app.yaml --version=${NEW_VERSION} --promote --quiet
        echo "Success:  Deployed: https://${{ secrets.PROJECT_ID }}.appspot.com"